name: Build AAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-aar:
    name: Build AAR
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the AAR
      - name: Build AAR
        run: ./gradlew :SmartFrameSDK:assembleRelease

      # List files in the AAR output directory for debugging
      - name: List files in AAR output directory
        run: ls -al SmartFrameSDK/build/outputs/aar/

      # Debug AAR Path
      - name: Debug AAR Path
        run: |
          if [ -f SmartFrameSDK/build/outputs/aar/SmartFrameSDK-release.aar ]; then
            echo "AAR file exists at the specified path."
          else
            echo "AAR file not found at SmartFrameSDK/build/outputs/aar/SmartFrameSDK-release.aar."
            exit 1
          fi

      # Upload the AAR as a workflow artifact
#      - name: Upload AAR
#        uses: actions/upload-artifact@v3
#        with:
#          name: SmartFrameSdk
#          path: SmartFrameSDK/build/outputs/aar/SmartFrameSDK-release.aar
#          retention-days: 3

      # Upload the AAR as a workflow artifact without ZIP compression
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: SmartFrameSdk
          path: SmartFrameSDK/build/outputs/aar/SmartFrameSDK-release.aar
          if-no-files-found: error
          retention-days: 3

      - name: Create a file
        run: echo "I won't live long" > my_file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my_file.txt
          retention-days: 5